### ISSUE TITLE
[System Request] for support of D% from Call of Cthulhu 7e

### ISSUE THREAD

**Issue by JornieNonsubia** [jacobwojoski/dice-stats#140]
CoC is using D% die instead of d100 which contain 1dT(10,20..) and 1d10(1-9).
![image](https://github.com/user-attachments/assets/7bed55e9-d3f2-4436-93f0-5e4cfece9fbd)
Right now Dice Stats is seeing those rolls as 2d10, but it should be d100
![image](https://github.com/user-attachments/assets/8729cc4d-2ddc-43a7-a060-b9c1e3f79b0e)

Would be great to add support for this die

**Comment by jacobwojoski** [comment]
Interesting. Will prob have to make a special parser for CoC then so might take a bit.

**Comment by JornieNonsubia** [comment]
> Interesting. Will prob have to make a special parser for CoC then so might take a bit.

Please take all the time you need, I'm looking forward to this feature. Meanwhile will do some translations I guess.

**Comment by jacobwojoski** [comment]
Are there any sort of advantage or disadvantage style mechanics that have you roll more of a specific type of die and take the better or worse result? 

Trying to come up with a good way to see if the roll is a d100 roll. Looking like ill need to convert the formula but if for some reason its not the form of '1dt +1d10' it would cause problems. Wondering if that roll formula would change for some reason and what it might change too. (Sorry not a CoC player)

**Comment by JornieNonsubia** [comment]
> Are there any sort of advantage or disadvantage style mechanics that have you roll more of a specific type of die and take the better or worse result?

Yeah, there are several advantages\disadvantages:
1) Basic Adv\disAdv - just add up to 2 more dt, so i.e. you roll 2dt 1d10 to see the %
2) you can add % to your skill value (does not impact dice)
3) I'm not sure how exactly it works but I guess it's similar one above but you add value to the roll itself.

Haven't seen any possibilities to change roll output, will check it later

**Comment by jacobwojoski** [comment]
So looking through the chat message it appears to select a die value before the message is created. There's not an easy way for me to know what of the dice are picked for the final result if they roll multiple dt's. Looks like the system selects the die to use before making the chat card. 

Ill need to submit something with the system developer to have an easy way to aquire the actual roll result otherwise the data just looks something like this giving values way over 100. 
![image](https://github.com/user-attachments/assets/28210d38-aea2-40e4-9ce5-26bb0d427c18)

**Comment by JornieNonsubia** [comment]
For now it would be great just to have statistics of of dt and d10 under d% tab and the data of successes (regular, hard extrim, crit) and failures/fumbles.

Due to how d% works in coc I think it would be pretty much it

**Comment by jacobwojoski** [comment]
Ususaly I try to chart the raw roll values from the dice not including modifiers but I can't easily do that for CoC until the system provides some update to how then generate chat messages. (I submitted a bug report but don't expect it to be a high priority)
Because of how they make the message I also cant easily get the degree success but might have a work around. 

I have 2 solutions I could implement in the meantime for graphing the result: 
1.) I can either graph the raw roll values but if you roll multiple dt it will always take the last dt value rolled
or 
2.) I can graph the result from the roll. But if anyone has a flat bonus or any other way to add values on top of the dice roll it will include that to the graphed value. EX: /r 1dt + 1d10 +5 + 1d7 would add the 5 and d7 to the result and graph the outcome rather than just the die roll.  (Any roll over 100 would be ignored)

**Comment by JornieNonsubia** [comment]
Second one sounds good, at least to me. Btw can Dice so nice! help with it? Almost all the games are using it, so while we are waiting for the fix maybe you can use it?

**Comment by jacobwojoski** [comment]
So Dice so Nice wont really help. All those modules use the dice values from the roll. I can get the dice values fine. The way they designed the system has it calculate the selected dice and degree success before it makes the message. 
They add all the dice values to the message but the formula isn't right. 

The system should use a `[ ( Xdtkh or Xdtkl ) + 1d10 ]` formaula but the message instead has a `(1dt + 1dt + 1dt + 1d10)` formula so the result and any outcome from the data is always some big number. They make the chat message and fill in that data wrong on the System side before the message is created and I access it. 

I made a release that takes the final result with the not handling modifiers solution if you wan't to try it. Release should be 1.20.0 It is only v12 supported as im not dealing with later versions for now.

**Comment by jacobwojoski** [comment]
Yeah you can parse the html if you want and save the data that way. I started a CoC7e system parser and that’s how I’m getting the total rn. 

So parsing the html would go there if you want to take a look and are feel adventurous. I’d look at the pf2e system message parser and the generic parser for ideas on how to set it up.  


using css classes is always a bit risky just from them changing so often and would rather wait for a system implement to spend time on it. But feel free to give it a shot.   


I also have plans to refactor how I’m making tabs to make them system specific instead of available to every system. And have a “system stats (charts) tab & system info (rolls data ex hits misses fails in table form)” so wasn’t trying to go crazy with UI stuff.   


I’ll probably make a new issue with the new scope in mind.

**Comment by jacobwojoski** [comment]
Looks like CoC added the new feature and its in the develop branch. Might be able to get this done soon

**Comment by JornieNonsubia** [comment]
Awesome! Thank you for letting me know
