### ISSUE TITLE
[System Request] Shadow of the Demon Lord

### ISSUE THREAD

**Issue by AetherianRPG** [jacobwojoski/dice-stats#31]
Greetings

At the moment, rolls made from character and creature sheets are not registered by the module. Is there any way to make it compatible with the system?

Thank you!

**Comment by jacobwojoski** [comment]
I can look into it. It really depends on how the system does rolls.

**Comment by AetherianRPG** [comment]
Thank you. I'm no dev so I can't help you with that. But I can explain the game rules of dice rolling if that helps you in any way. Just let me know!

**Comment by jacobwojoski** [comment]
Sounds good. I reach out and let you know what I find after I do some research

**Comment by jacobwojoski** [comment]
Looked into it. But unfortunately wont be able to get it working without a lot of work on my end.

I cant find the roll data in the message basically anywhere.

It seems like instead of adding roll data into the normal area in messages like most systems they make a custom string to be displayed. 

To manually parse their custom text to find the result and the die type would be alot of work and break every time they changed how messages were made. Unfortunately its a but too much of a time sink for me rn. 

I did leave a bug as a question on the system page so if they get back to me with some info about somthing I didnt see or add the data to the rolls section of the message then I can get it working.

But as for now sorry for the bad news.
